FROM node:20-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    bash \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/* && \
    npm install -g @nestjs/cli

USER node

WORKDIR /app

COPY --chown=node:node package*.json tsconfig.json tsconfig.build.json nest-cli.json ./

RUN npm install

COPY --chown=node:node .docker /app/.docker

CMD ["bash", "/app/.docker/start.sh"]
