site_name: G7 - MonitoreSeuTreino
site_description: Documentação de Padrões de Projeto GoF
site_url: https://unbarqdsw2025-1-turma01.github.io/2026.1-T01-_G7_MonitoreSeuTreino_Entrega_03/

docs_dir: content
site_dir: ../site

theme:
  name: material
  language: pt-BR
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - toc.integrate

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - tables

nav:
  - Início: index.md

  - Projeto:
      - Visão Geral: projeto/visao-geral.md
      - Metodologia: projeto/metodologia.md
      - Onboarding: projeto/onboarding.md
      - Exercícios: projeto/exercicios.md

  - Arquitetura:
      - Visão Geral: arquitetura/visao-geral.md
      - Stack: arquitetura/stack.md
      - Rastreabilidade dos GoFs: arquitetura/rastreabilidade-gofs.md

  - Padrões de Projeto:
      - 3. Padrões de Projeto: padroes-de-projeto/3-padroes-de-projeto.md
      - 3.1 GoFs Criacionais: padroes-de-projeto/3-1-gofs-criacionais.md
      - 3.2 GoFs Estruturais: padroes-de-projeto/3-2-gofs-estruturais.md
      - 3.3 GoFs Comportamentais: padroes-de-projeto/3-3-gofs-comportamentais.md
      - 3.4 Participações: padroes-de-projeto/3-4-participacoes-padroes.md
      - 3.5 Iniciativas Extras: padroes-de-projeto/3-5-iniciativas-extras.md

  - Evidências:
      - Execução: evidencias/execucao.md
      - Commits: evidencias/commits.md
      - Vídeos: evidencias/videos.md
      - Links: evidencias/links.md

  - Referências:
      - Bibliografia: referencias/bibliografia.md
